var figura = new THREE.Shape();
figura.moveTo(0, 30);
figura.lineTo(8.82, 12.14);
figura.lineTo(28.53, 9.27);
figura.lineTo(14.27, -4.64);
figura.lineTo(17.63, -24.27);
figura.lineTo(0, -15);
figura.lineTo(-17.63, -24.27);
figura.lineTo(-14.27, -4.64);
figura.lineTo(-28.53, 9.27);
figura.lineTo(-8.82, 12.14);
figura.lineTo(0, 30);

var forma = new THREE.ShapeGeometry(figura);
var malla = new THREE.Mesh(forma);
var escena = new THREE.Scene();
escena.add(malla);
var camara = new THREE.PerspectiveCamera();
camara.position.z = 100;
var renderizador = new THREE.WebGLRenderer();
renderizador.setSize( window.innerHeight*.95,  window.innerHeight*.95 );
document.body.appendChild( renderizador.domElement );
renderizador.render( escena, camara );
